######################################################
# Copyright 2021. Nifanin Konstantin
# Licensed under the Apache License, 
# Version 2.0 (the «License»);
#
# List of autors (add your name here if edit):
# - Nifanin Konstantin (https://github.com/Piknik1990)
######################################################

# XML-generator
import xml.etree.ElementTree as ET
from xml.dom import minidom

# Date-Time-generator
from datetime import datetime

def date_now():
    # Print current time-date in ISO-format
    # Parameters: node
    # Output: date in ISO-format
    # Example: date_now() -> '2021-07-20T22:30:20.340045'
    # Errors: none
    # Warnings: none   
    dateTimeNowUnFormatted = datetime.now()
    return dateTimeNowUnFormatted.isoformat()


def xml_prettify(untostringXml):
    # Get XML and return this one in pretty format
    # Parameters: tostringXml - unpretty, untostring XML
    # Output: Pretty XML
    # Example: xml_prettify(tostringXml) ->
    #          -> <mxfile
    #          ->   host="Electron" 
    #          ->   modified="2021-07-20T19:09:04.198Z"
    #          -> ...
    #          -> </mxfile>
    # Errors: input tostringXml is not provided (Fatal)
    #         input tostringXml is not untostring (Fatal)
    # Warnings: none
    if not untostringXml:
        pig_error("function 'xml_prettify': tostringXml is not provided", "dev")
    try:      
        rough_string = ET.tostring(untostringXml, 'utf-8')
    except Exception:
        pig_error("function 'xml_prettify': tostringXml have not XML format", "dev")
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml()


def drawio_file_xml_creater(pretty=True):
    # Create XML-format for save to file
    # Parameters: pretty (bool) - Pretty format of XML or no
    # Output: Draw.io XML-format
    # Examples: drawio_file_xml_creater() -> <?xml version="1.0" ?>
    #                                     ->    <mxfile host="Electron" modified="2021-07-21T01:16:09.317754" ....>
    #                                     ->    <!--Generated by Sec10-->
    #                                     -> </mxfile>
    #          drawio_file_xml_creater(False) -> b'<mxfile host="Electron" modified="2021-07-21T01:16:18.524426" ...><!--Generated by Sec10--></mxfile>'    
    # Errors: none
    # Warnings: none
    comment = ET.Comment('Generated by Sec10')
    mxfile = ET.Element("mxfile", 
        host="Electron", 
        modified=date_now(), 
        agent="5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) draw.io/14.4.3 Chrome/87.0.4280.141 Electron/11.3.0 Safari/537.36", 
        etag="Aqg4BSG_KBGXFY7UXDhO", 
        version="14.4.3", 
        type="device")
    mxfile.append(comment)
    if pretty:
        return xml_prettify(mxfile)
    else:
        return ET.tostring(mxfile)
